//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppEFExmple
{
    using System;
    using System.Collections.Generic;
    
    public partial class faculty
    {
        public int fid { get; set; }
        public string fname { get; set; }
        public int fsal { get; set; }
        public override string ToString ()
        {
            return $"Facult ID : {fid}\tFaculty Name : {fname}\tSalary : {fsal}";
        }
    }
}
